/*require("./common.js");
require("./ad.js");
require("./top.js");
require("./recomm.js");
require("./nav.js");
require("./relate.js");
require("./trip.js");
require("./visa.js");
require("./book_note.js");
require("./attach_pro.js");
require("./travel.js");
require("./data.js");
require("./review.js");
require("./module_slider.js");
require("./tongji.js");
require("./buried_point.js");*/
/*require("../../public/utility/js/cruise.utitlty.js");
require("../../public/fish/js/fish.once.js");
require("../../public/fish/js/fish.scroll.js");
require("../../public/fish/js/fish.spinner.js");
require("../../public/fish/js/fish.calendar.js");*/


require("./ad.js");
require("./common.js");
require("./top.js");
require("./recomm.js");
require("./nav.js");
require("./relate.js");
require("./trip.js");
require("./visa.js");
require("./book_note.js");

require("./attach_pro.js");
require("./travel.js");
require("./data.js");
require("./review.js");
require("./module_slider.js");
require("./tongji.js");
require("./buried_point.js");